version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/werewolf
      - "bundle:/boat-community/vendor/bundle"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - default
      - shared-network

volumes:
  db-volume:
  bundle:

networks:
  shared-network:
    external: true
